services:
  # Serviço: OnlyOffice Document Server
  tinymce:
    image: nginx:latest         # Usa a imagem oficial do Nginx
    container_name: tinymce
    ports:
      - "8082:80"               # Mapeia a porta 80 do contêiner para a porta 8080 no host
    volumes:
      - ./tinymce/dist:/usr/share/nginx/html       # Monta os arquivos do editor (somente leitura)
      - ./configs/nginx:/etc/nginx/conf.d  # Monta a configuração personalizada do Nginx (somente leitura)
    depends_on:
      - keycloak
      
  # Serviço: Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_DB_SCHEMA: keycloak # Define o esquema para o Keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"  # Porta para acessar o Keycloak
    depends_on:
      - postgres
    volumes:
      - ./configs/keycloak/keycloak-realm.json:/opt/keycloak/data/import/realm.json
    command: "start-dev --import-realm --spi-login-cookie-same-site=None --spi-login-cookie-path=/ --spi-login-cookie-secure=true"

  # Serviço: PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: useradmin123
      POSTGRES_DB: dbdsg
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./configs/db/init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql # Monta o script de inicialização

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase
    depends_on:
      - tinymce
    volumes:
      - ./configs/liquibase/onlyoffice:/liquibase/changelog
    entrypoint: ["liquibase"]
    command: ["--search-path=/liquibase/changelog/","--defaults-file=/liquibase/changelog/liquibase.properties", "update"]
    #command: ["--changelog-file=/liquibase/changelog/changelog-master.xml", "update"]
    # command: ["update"]