quarkus.datasource.db-kind = postgresql
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/postgres
quarkus.hibernate-orm.database.generation = update
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQL10Dialect
%dev.quarkus.datasource.username = cadastro
%dev.quarkus.datasource.password = cadastro
%dev.quarkus.hibernate-orm.log.sql = false

mp.jwt.verify.issuer=http://localhost:8180/auth/realms/ifood
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm5tDeZzxppS8OmHa3ETImawpIwa/hMNMXOzXdSskHKbbDFrUKtWcwFYdb1Ctr8TZbYkHmwk4OnmNyeXIK1rZM3RLcB2S2A4rg/7CSGneZaopUJUFhTHVKu6l72nSxOI7ugfl3AJpaLHx6yZSsUICG1uqgVK+RyiVvpDfEPKDPGSkvik5Tp9ELXCxsT2uKEz3dCDoTJ4teIZvvOB84AZTb0ab1MSBF3teUqmK7dP/cIEzgTWy0zwoaRuYjrIj91W/h0CtwysQgi1KKz7cAeRNU8Sv95VOrBygwvoBWPx3QB9CJtJRgtSUyrWrN7bVmsYafiZ/ejsc3SW7C0JKhjz97QIDAQAB

%test.quarkus.datasource.username = cadastro
%test.quarkus.datasource.password = cadastro
%test.quarkus.hibernate-orm.log.sql = false